#!/bin/sh

DATE=`date "+%Y%m%d"`
NAME="marshmallow_h-${DATE}-src"

exec git ls-files --cached --full-name --no-empty-directory | \
xargs tar --transform="s,^,${NAME}/," --exclude=".git*" -cvf - | \
xz -e - > "${NAME}.tar.xz"

