set(MARSHMALLOW_VIEWPORT_VSYNC  "0" CACHE STRING "")

set(MARSHMALLOW_VIEWPORT_DUMMY  OFF CACHE BOOL "")
set(MARSHMALLOW_VIEWPORT_OPENGL ON  CACHE BOOL "")

set(MARSHMALLOW_OPENGL_EGL      OFF CACHE BOOL "")
set(MARSHMALLOW_OPENGL_ES2      OFF CACHE BOOL "")
set(MARSHMALLOW_OPENGL_QT4      ON  CACHE BOOL "")
