set(CMAKE_C_COMPILER "/usr/bin/clang" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER "/usr/bin/clang++" CACHE STRING "" FORCE)
#set(CMAKE_C_FLAGS "-m32" CACHE STRING "" FORCE)
#set(CMAKE_CXX_FLAGS "-m32" CACHE STRING "" FORCE)
set(CMAKE_COMPILER_IS_GNUCC TRUE CACHE BOOL "" FORCE)
set(CMAKE_COMPILER_IS_GNUXX TRUE CACHE BOOL "" FORCE)

set(BUILD_UNIT_TESTS OFF CACHE BOOL "" FORCE)
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "" FORCE)
set(MARSHMALLOW_DEBUG OFF CACHE BOOL "" FORCE)
set(MARSHMALLOW_DEBUG_VERBOSITY "0" CACHE STRING "" FORCE)

set(USING_CLANG ON CACHE BOOL "" FORCE)
mark_as_advanced(USING_CLANG)
