#set(CMAKE_C_FLAGS "-m32" CACHE STRING "" FORCE)
#set(CMAKE_CXX_FLAGS "-m32" CACHE STRING "" FORCE)

set(BUILD_UNIT_TESTS OFF CACHE BOOL "" FORCE)
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "" FORCE)
set(MARSHMALLOW_DEBUG OFF CACHE BOOL "" FORCE)
set(MARSHMALLOW_DEBUG_VERBOSITY "0" CACHE STRING "" FORCE)

set(MARSHMALLOW_VIEWPORT_OPENGL ON CACHE BOOL "" FORCE)
set(MARSHMALLOW_OPENGL_QT4 ON CACHE BOOL "" FORCE)
