set(CMAKE_C_COMPILER   "/usr/bin/clang"   CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER "/usr/bin/clang++" CACHE STRING "" FORCE)

set(CMAKE_COMPILER_IS_GNUCC TRUE CACHE BOOL "" FORCE)
set(CMAKE_COMPILER_IS_GNUXX TRUE CACHE BOOL "" FORCE)

set(USING_CLANG ON CACHE INTERNAL "" FORCE)
