set(MARSHMALLOW_VIEWPORT_DUMMY  OFF CACHE BOOL "")
set(MARSHMALLOW_VIEWPORT_OPENGL ON  CACHE BOOL "")

set(MARSHMALLOW_OPENGL_EGL      ON  CACHE BOOL "")
set(MARSHMALLOW_OPENGL_ES2      ON  CACHE BOOL "")
set(MARSHMALLOW_OPENGL_X11      ON  CACHE BOOL "")
