# MARSHMALLOW
set(MARSHMALLOW_AUDIO_ALSA          OFF  CACHE BOOL "")
set(MARSHMALLOW_AUDIO_DUMMY         ON   CACHE BOOL "")

set(MARSHMALLOW_INPUT_LINUX_EVDEV   ON   CACHE BOOL "")
set(MARSHMALLOW_EVDEV_JOYSTICK      ON   CACHE BOOL "")
set(MARSHMALLOW_EVDEV_KEYBOARD      ON   CACHE BOOL "")

set(MARSHMALLOW_GRAPHICS_TITLE     "Marshmallow Raspberry Pi" CACHE STRING "")
set(MARSHMALLOW_GRAPHICS_WIDTH     "720" CACHE STRING "")
set(MARSHMALLOW_GRAPHICS_HEIGHT    "480" CACHE STRING "")
set(MARSHMALLOW_GRAPHICS_DEPTH     "16"  CACHE STRING "")
set(MARSHMALLOW_GRAPHICS_FULLSCREEN ON   CACHE BOOL   "")

set(MARSHMALLOW_GRAPHICS_DUMMY      OFF  CACHE BOOL   "")
set(MARSHMALLOW_GRAPHICS_OPENGL     ON   CACHE BOOL   "")

set(MARSHMALLOW_OPENGL_EGL          ON   CACHE BOOL   "")
set(MARSHMALLOW_OPENGL_ES2          ON   CACHE BOOL   "")
set(MARSHMALLOW_OPENGL_VC           ON   CACHE BOOL   "")

set(MARSHMALLOW_CONTRIB_LIBOGG      OFF  CACHE BOOL   "")
set(MARSHMALLOW_CONTRIB_LIBPNG      OFF  CACHE BOOL   "")
set(MARSHMALLOW_CONTRIB_LIBVORBIS   OFF  CACHE BOOL   "")
set(MARSHMALLOW_CONTRIB_ZLIB        OFF  CACHE BOOL   "")

# CMAKE
#set(CMAKE_C_FLAGS "-mfpu=vfp -mfloat-abi=hard"   CACHE STRING "")
set(CMAKE_C_FLAGS_RELEASE "-fomit-frame-pointer"                    CACHE STRING "")
#set(CMAKE_CXX_FLAGS "-mfpu=vfp -mfloat-abi=hard" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELEASE "-fomit-frame-pointer"                  CACHE STRING "")

set(CMAKE_FIND_ROOT_PATH   "/opt/vc"           CACHE INTERNAL "")
set(CMAKE_SKIP_BUILD_RPATH  FALSE              CACHE INTERNAL "")
set(CMAKE_INSTALL_RPATH    "./lib:/opt/vc/lib" CACHE STRING   "")
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH FALSE    CACHE INTERNAL "")
set(CMAKE_BUILD_WITH_INSTALL_RPATH    TRUE     CACHE INTERNAL "")

