set(MARSHMALLOW_GRAPHICS_VSYNC  "0" CACHE STRING "")

set(MARSHMALLOW_GRAPHICS_DUMMY  OFF CACHE BOOL "")
set(MARSHMALLOW_GRAPHICS_OPENGL ON  CACHE BOOL "")

set(MARSHMALLOW_OPENGL_EGL      OFF CACHE BOOL "")
set(MARSHMALLOW_OPENGL_ES2      OFF CACHE BOOL "")
set(MARSHMALLOW_OPENGL_SDL      ON  CACHE BOOL "")
