set(MARSHMALLOW_BUILD_TITLE "Marshmallow Wii" CACHE STRING "")

set(MARSHMALLOW_VIEWPORT_WIDTH     "720" CACHE STRING "")
set(MARSHMALLOW_VIEWPORT_HEIGHT    "480" CACHE STRING "")
set(MARSHMALLOW_VIEWPORT_DEPTH     "16"  CACHE STRING "")
set(MARSHMALLOW_VIEWPORT_REFRESH   "60"  CACHE STRING "")
set(MARSHMALLOW_VIEWPORT_FULLSCREEN ON   CACHE BOOL   "")

set(MARSHMALLOW_VIEWPORT_GRAB_INPUT ON   CACHE BOOL   "")

set(MARSHMALLOW_VIEWPORT_DUMMY      OFF  CACHE BOOL   "")
set(MARSHMALLOW_VIEWPORT_GX         ON   CACHE BOOL   "")
