set(CMAKE_BUILD_TYPE  "Release" CACHE STRING "")
set(BUILD_UNIT_TESTS  OFF       CACHE BOOL   "")
set(MARSHMALLOW_DEBUG OFF       CACHE BOOL   "")
set(MARSHMALLOW_DEBUG_VERBOSITY "0"       CACHE STRING "")
