set(MARSHMALLOW_BLACKBERRY TRUE CACHE BOOL "Marshmallow for BlackBerry" FORCE)

set(MARSHMALLOW_AUDIO_DUMMY         OFF   CACHE BOOL   "")
set(MARSHMALLOW_AUDIO_OPENAL        ON    CACHE BOOL   "")

set(MARSHMALLOW_GRAPHICS_TITLE     "BlackBerry Marshmallow" CACHE STRING "")
set(MARSHMALLOW_GRAPHICS_WIDTH     "1024" CACHE STRING "")
set(MARSHMALLOW_GRAPHICS_HEIGHT    "600"  CACHE STRING "")
set(MARSHMALLOW_GRAPHICS_DEPTH     "24"   CACHE STRING "")
set(MARSHMALLOW_GRAPHICS_FULLSCREEN ON    CACHE BOOL   "")

set(MARSHMALLOW_GRAPHICS_DUMMY      OFF   CACHE BOOL   "")
set(MARSHMALLOW_GRAPHICS_OPENGL     ON    CACHE BOOL   "")

set(MARSHMALLOW_OPENGL_EGL          ON    CACHE BOOL   "")
set(MARSHMALLOW_OPENGL_ES2          ON    CACHE BOOL   "")
set(MARSHMALLOW_OPENGL_BB           ON    CACHE BOOL   "")

set(MARSHMALLOW_CONTRIB_LIBPNG      OFF   CACHE BOOL   "")
set(MARSHMALLOW_CONTRIB_ZLIB        OFF   CACHE BOOL   "")

set(CMAKE_SKIP_BUILD_RPATH            TRUE  CACHE INTERNAL "")
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH FALSE CACHE INTERNAL "")
set(CMAKE_BUILD_WITH_INSTALL_RPATH    TRUE  CACHE INTERNAL "")

