# MARSHMALLOW
set(MARSHMALLOW_VIEWPORT_TITLE     "BlackBerry Marshmallow" CACHE STRING "")
set(MARSHMALLOW_VIEWPORT_WIDTH     "1024" CACHE STRING "")
set(MARSHMALLOW_VIEWPORT_HEIGHT    "600"  CACHE STRING "")
set(MARSHMALLOW_VIEWPORT_DEPTH     "24"   CACHE STRING "")
set(MARSHMALLOW_VIEWPORT_FULLSCREEN ON    CACHE BOOL   "")

set(MARSHMALLOW_VIEWPORT_DUMMY      OFF   CACHE BOOL   "")
set(MARSHMALLOW_VIEWPORT_OPENGL     ON    CACHE BOOL   "")

set(MARSHMALLOW_OPENGL_EGL          ON    CACHE BOOL   "")
set(MARSHMALLOW_OPENGL_ES2          ON    CACHE BOOL   "")
set(MARSHMALLOW_OPENGL_QNX          ON    CACHE BOOL   "")

set(MARSHMALLOW_WITH_BOX2D          ON    CACHE BOOL   "")
set(MARSHMALLOW_WITH_LUA            OFF   CACHE BOOL   "")

set(CMAKE_SKIP_BUILD_RPATH            TRUE  CACHE INTERNAL "")
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH FALSE CACHE INTERNAL "")
set(CMAKE_BUILD_WITH_INSTALL_RPATH    TRUE  CACHE INTERNAL "")

