set(MARSHMALLOW_VIEWPORT_VSYNC      OFF  CACHE BOOL   "")

set(MARSHMALLOW_VIEWPORT_DUMMY      OFF  CACHE BOOL   "")
set(MARSHMALLOW_VIEWPORT_OPENGL     ON   CACHE BOOL   "")

set(MARSHMALLOW_OPENGL_ES2_EGL      OFF  CACHE BOOL   "")
set(MARSHMALLOW_OPENGL_QT4          ON   CACHE BOOL   "")
