set(CMAKE_C_COMPILER "/usr/bin/gcc" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER "/usr/bin/g++" CACHE STRING "" FORCE)
#set(CMAKE_C_FLAGS "-m32" CACHE STRING "" FORCE)
#set(CMAKE_CXX_FLAGS "-m32" CACHE STRING "" FORCE)

set(BUILD_UNIT_TESTS ON CACHE BOOL "" FORCE)
set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "" FORCE)
set(MARSHMALLOW_DEBUG ON CACHE BOOL "" FORCE)
set(MARSHMALLOW_DEBUG_VERBOSITY "1" CACHE STRING "" FORCE)
