set(MARSHMALLOW_BUILD_TITLE "Marshmallow HARMATTAN_ARMEL" CACHE STRING "")
set(BUILD_SHARED_LIBS OFF CACHE BOOL "")

set(MARSHMALLOW_VIEWPORT_WIDTH     "854" CACHE STRING "")
set(MARSHMALLOW_VIEWPORT_HEIGHT    "480" CACHE STRING "")
set(MARSHMALLOW_VIEWPORT_DEPTH     "16"  CACHE STRING "")
set(MARSHMALLOW_VIEWPORT_REFRESH   "60"  CACHE STRING "")
set(MARSHMALLOW_VIEWPORT_VSYNC     "1"   CACHE STRING "")
set(MARSHMALLOW_VIEWPORT_FULLSCREEN ON   CACHE BOOL   "")
set(MARSHMALLOW_VIEWPORT_GRAB_INPUT OFF  CACHE BOOL   "")

set(MARSHMALLOW_VIEWPORT_DUMMY      OFF  CACHE BOOL   "")
set(MARSHMALLOW_VIEWPORT_OPENGL     ON   CACHE BOOL   "")

set(MARSHMALLOW_OPENGL_EGL          ON   CACHE BOOL   "")
set(MARSHMALLOW_OPENGL_ES2          ON   CACHE BOOL   "")
set(MARSHMALLOW_OPENGL_X11          ON   CACHE BOOL   "")
