set(MARSHMALLOW_ANDROID TRUE CACHE BOOL "Marshmallow for Android" FORCE)

# CMAKE
set(BUILD_SHARED_LIBS              OFF    CACHE BOOL     "")
set(CMAKE_SKIP_BUILD_RPATH         TRUE   CACHE INTERNAL "")

# ANDROID
set(ANDROID_NATIVE_API_LEVEL       "9"    CACHE STRING "")

# MARSHMALLOW
set(MARSHMALLOW_GRAPHICS_TITLE     "Marshmallow Android" CACHE STRING "")
set(MARSHMALLOW_GRAPHICS_WIDTH     "1024" CACHE STRING "")
set(MARSHMALLOW_GRAPHICS_HEIGHT    "600"  CACHE STRING "")
set(MARSHMALLOW_GRAPHICS_DEPTH     "24"   CACHE STRING "")
set(MARSHMALLOW_GRAPHICS_FULLSCREEN ON    CACHE BOOL   "")

set(MARSHMALLOW_GRAPHICS_DUMMY      OFF   CACHE BOOL   "")
set(MARSHMALLOW_GRAPHICS_OPENGL     ON    CACHE BOOL   "")

set(MARSHMALLOW_OPENGL_EGL          ON    CACHE BOOL   "")
set(MARSHMALLOW_OPENGL_ES2          ON    CACHE BOOL   "")
set(MARSHMALLOW_OPENGL_JNI          ON    CACHE BOOL   "")

set(MARSHMALLOW_DEMO_CWD_OVERRIDE  OFF     CACHE BOOL   "")

