set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS} -W -Wall"   CACHE STRING "")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -W -Wall" CACHE STRING "")

set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "")
set(BUILD_UNIT_TESTS  ON CACHE BOOL "")
set(MARSHMALLOW_DEBUG ON CACHE BOOL "")
set(MARSHMALLOW_DEBUG_VERBOSITY "1" CACHE STRING "")
