set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR $ENV{RPITOOLCHAIN_TARGET})

set(RPIFIRMWARE         $ENV{RPIFIRMWARE}                                 CACHE STRING "" FORCE)
set(RPITOOLCHAIN        $ENV{RPITOOLCHAIN}                                CACHE STRING "" FORCE)
set(RPITOOLCHAIN_HOST   $ENV{RPITOOLCHAIN_HOST}                           CACHE STRING "" FORCE)
set(RPITOOLCHAIN_TARGET $ENV{RPITOOLCHAIN_TARGET}                         CACHE STRING "" FORCE)

set(CMAKE_CXX_COMPILER ${RPITOOLCHAIN}/bin/${RPITOOLCHAIN_TARGET}-g++     CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER   ${RPITOOLCHAIN}/bin/${RPITOOLCHAIN_TARGET}-gcc     CACHE STRING "" FORCE)
set(CMAKE_LINKER       ${RPITOOLCHAIN}/bin/${RPITOOLCHAIN_TARGET}-ld      CACHE STRING "" FORCE)

set(CMAKE_AR           ${RPITOOLCHAIN}/bin/${RPITOOLCHAIN_TARGET}-ar      CACHE STRING "" FORCE)
set(CMAKE_NM           ${RPITOOLCHAIN}/bin/${RPITOOLCHAIN_TARGET}-nm      CACHE STRING "" FORCE)
set(CMAKE_OBJCOPY      ${RPITOOLCHAIN}/bin/${RPITOOLCHAIN_TARGET}-objcopy CACHE STRING "" FORCE)
set(CMAKE_OBJDUMP      ${RPITOOLCHAIN}/bin/${RPITOOLCHAIN_TARGET}-objdump CACHE STRING "" FORCE)
set(CMAKE_RANLIB       ${RPITOOLCHAIN}/bin/${RPITOOLCHAIN_TARGET}-ranlib  CACHE STRING "" FORCE)
set(CMAKE_STRIP        ${RPITOOLCHAIN}/bin/${RPITOOLCHAIN_TARGET}-strip   CACHE STRING "" FORCE)

set(CMAKE_FIND_ROOT_PATH "${RPITOOLCHAIN}/${RPITOOLCHAIN_TARGET}/sys-root" "${RPIFIRMWARE}/opt/vc")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
