set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)

if ("$ENV{RPI_FIRMWARE_DIR}" STREQUAL ""
    OR "$ENV{RPI_STAGING_DIR}" STREQUAL ""
    OR "$ENV{RPI_SYSTEM_PROCESSOR}" STREQUAL ""
    OR "$ENV{RPI_TOOLCHAIN_DIR}" STREQUAL "")
	message(FATAL_ERROR "\n*** Invalid toolchain environment ***\n"
	                    "Please source the toolchain environment file.\n")
endif()
set(CMAKE_SYSTEM_PROCESSOR $ENV{RPI_SYSTEM_PROCESSOR})

set(RPI_FIRMWARE_DIR  $ENV{RPI_FIRMWARE_DIR}  CACHE INTERNAL "" FORCE)
set(RPI_STAGING_DIR   $ENV{RPI_STAGING_DIR}   CACHE INTERNAL "" FORCE)
set(RPI_TOOLCHAIN_DIR $ENV{RPI_TOOLCHAIN_DIR} CACHE INTERNAL "" FORCE)

set(CMAKE_FIND_ROOT_PATH ${RPI_STAGING_DIR}
                         ${RPI_FIRMWARE_DIR} CACHE INTERNAL "")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(BUILD_UNIT_TESTS OFF CACHE BOOL "")
