set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR $ENV{RPITOOLCHAIN_TARGET})

if ("$ENV{RPIFIRMWARE}" STREQUAL ""
    OR "$ENV{RPITOOLCHAIN}" STREQUAL ""
    OR "$ENV{RPITOOLCHAIN_HOST}" STREQUAL ""
    OR "$ENV{RPITOOLCHAIN_TARGET}" STREQUAL "")
	message(FATAL_ERROR "\n*** Invalid toolchain environment ***\n"
	                    "Please source the toolchain environment file.\n")
endif()

set(RPIFIRMWARE         $ENV{RPIFIRMWARE}         CACHE INTERNAL "" FORCE)
set(RPITOOLCHAIN        $ENV{RPITOOLCHAIN}        CACHE INTERNAL "" FORCE)
set(RPITOOLCHAIN_HOST   $ENV{RPITOOLCHAIN_HOST}   CACHE INTERNAL "" FORCE)
set(RPITOOLCHAIN_TARGET $ENV{RPITOOLCHAIN_TARGET} CACHE INTERNAL "" FORCE)

set(CMAKE_C_COMPILER   ${RPITOOLCHAIN}/bin/${RPITOOLCHAIN_TARGET}-gcc CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER ${RPITOOLCHAIN}/bin/${RPITOOLCHAIN_TARGET}-g++ CACHE FILEPATH "" FORCE)

set(CMAKE_FIND_ROOT_PATH ${RPITOOLCHAIN}
                         ${RPITOOLCHAIN}/${RPITOOLCHAIN_TARGET}/sysroot
                         ${RPIFIRMWARE}/opt/vc CACHE INTERNAL "")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
